### ISSUE TITLE
Error handling for boost:package goal

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/boost-maven#69]
The question came up whether boost:package should be able to be called directly, given that the SB maven plugin package goal is required to be called first. We should determine if we are in the SB scenario, and if so check that the Uber jar is either the SB Uber jar or the Liberty Boost Uber jar before attempting to package. If it is not, an error should be thrown (or would we want to call the SB maven plugin package goal ourselves in that case?).

**Comment by scottkurz** [comment]
Or maybe if we can't package it identically we should fall fast?  Not sure

**Comment by scottkurz** [comment]
Similar concerns could be raised for `mvn boost:start` without a package...

**Comment by barecode** [comment]
I actually just tried `mvn boost:start`without a package and unless I screwed it up it just starts an empty Liberty server.

In either case, `mvn clean io.openliberty.boost:boost-maven-plugin:0.1:package` results in a rather ugly error message and minimally improving that would be good. Current error message is:

```
[ERROR] Failed to execute goal io.openliberty.boost:boost-maven-plugin:0.1:package (default-cli) on project gs-spring-boot: Execution default-cli of goal io.openliberty.boost:boost-maven-plugin:0.1:package failed.: NullPointerException -> [Help 1]
```

**Comment by chyt** [comment]
@scottkurz Like @barecode said, I believe that `boost:start` without a repackage is working as intended. The goal, when executed alone, doesn't have any context about the application and it's only purpose is to start our managed `BoostServer`, which is does properly.

I have an incoming PR to fix the `boost:package` errors Mike described.

**Comment by scottkurz** [comment]
@chyt   I don't recall any conversation about what `boost:start` should do in this case.   Having read your comments, though, it seems fine.   

One concern I had was that the install done by the `liberty:start` goal would get cached and wouldn't really be usable in boost scenarios.  I was just guessing there was an issue and that we should fail fast.

However, after actually trying it, it looks like the install done by `liberty:start-server` will get overwritten by the install done by `boost:package` driving `liberty:create-server`.   

So that one concern is a non-issue.. and this seems fine as a sensible behavior when you use the plugin in an unintended way.
